---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pidhpa-operator.fullname" . }}-list-role
rules:
  - apiGroups: ["pidscaler.ts"]
    resources: ["pidscalers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pidhpa-operator.fullname" . }}-list-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pidhpa-operator.fullname" . }}-list-role
subjects:
  - kind: ServiceAccount
    name: {{ include "pidhpa-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
