# permissions for end users to view pidscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pidhpa
    app.kubernetes.io/managed-by: kustomize
  name: pidscaler-viewer-role
rules:
- apiGroups:
  - pidscaler.ts
  resources:
  - pidscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pidscaler.ts
  resources:
  - pidscalers/status
  verbs:
  - get
