---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - pidscaler.ts
  resources:
  - pidscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pidscaler.ts
  resources:
  - pidscalers/finalizers
  verbs:
  - update
- apiGroups:
  - pidscaler.ts
  resources:
  - pidscalers/status
  verbs:
  - get
  - patch
  - update
