# Default values for pidhpa-operator.
replicaCount: 1

image:
  repository: ghcr.io/timson/pidhpa
  tag: test-cicd
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: pidhpa-operator

rbac:
  create: true

resources:
  limits:
    cpu: "500m"
    memory: "128Mi"
  requests:
    cpu: "100m"
    memory: "64Mi"

watchNamespace: "" # Set to a specific namespace if you want to watch only that namespace, or "" for all namespaces
